### ISSUE TITLE
Appium 1.3.6 release

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium-dot-exe#134]
https://discuss.appium.io/t/appium-1-3-6-release/3179

**Comment by Astro03** [comment]
unfortunately this relates to #97 where the node modules exceed the path allowed for a zip application on windows.

**Comment by 0x1mason** [comment]
@Astro03 submitted #136 to fix #97

**Comment by Astro03** [comment]
pull successful but this is no longer valid.. #138 is latest
