### ISSUE TITLE
Installer upgrades should detect existing installation location

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium-dot-exe#137]
I think the way to handle upgrades is:

* Appium.exe downloads the new version
* launches the installer with args sim to [/SP- /silent /noicons /closeapplications "/dir=expand:{pf}\My Program"](http://www.jrsoftware.org/ishelp/topic_technotes.htm)
* Appium.exe exits and lets installer run.

I'm also wondering if there shouldn't be an option to update Appium separately, which would mean you only need to offer new releases when there are UI changes.

**Comment by Astro03** [comment]
I like that!

So one option to update the appium server and one option to update the
appium application!

the only thing is we need to keep track of which version is what then
(which would be easy too).
