### ISSUE TITLE
Please release .exe for 1.4.13

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-dot-exe#157]
We have released Appium 1.4.13.

**Comment by curtissiemens** [comment]
Yes, I can't get iOS 9.0 Simulators to work using Appium.app 1.4.8 (current release).

**Comment by Astro03** [comment]
I'll release later today. 

Ciao,
Astro
Sent from my phone

On Oct 8, 2015, at 13:01, Curtis Siemens <notifications@github.com> wrote:

Yes, I can't get iOS 9.0 Simulators to work using Appium.app 1.4.8 (current release).

**Comment by Astro03** [comment]
released. you can download the installer at http://appium.io/downloads.html or just upgrade through the app -> file->check for upgrade.

**Comment by curtissiemens** [comment]
OS-X version of Appium.app is not built, just the windows version.

**Comment by Astro03** [comment]
@curtissiemens that should be done in the other channel (appium-dot-app). I do not build and publish that application. @penguinho is the one in charge of that and can prob do it after he gets back from travels.
