### ISSUE TITLE
Windows installer contains deprecated version of node

### ISSUE THREAD

**Issue by yahman72** [appium/appium-dot-exe#167]
Appium v1.4.13.1 installer (the windows one) comes with a deprecated version of node.

<pre>
Checking if an update is available
Update not available
Launching Appium server with command: C:\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
<b>warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!`</b>
</pre>

FYI: Issue originally opened for wrong project (https://github.com/appium/appium/issues/5862).

**Comment by Astro03** [comment]
Can you try something for me? go to https://github.com/appium/appium-dot-exe and read the "To Update Appium Server manually" that should update the node and server for you. 

Let me know what happens. I will update if this works. (sorry no time to test myself right now)

**Comment by Astro03** [comment]
btw, i just checked, 1.4.16.1 is the latest. plz download the latest from http://appium.io/downloads.html

open this issue back up if it's still persistent. thx

**Comment by yahman72** [comment]
FYI: I already had the Node updated. 
This issue was opened for the fact that the distribution contained a deprecated version i.e. it should not be necessary to upgrade right after installation.

**Comment by Astro03** [comment]
I agree with you.. but are you using the right installer? 
v1.4.16.1 was released on 2015.12.08
v1.4.13.1 was released on 2015.10.09

I'm a bit confused, does the latest installer have the bad version too?

**Comment by yahman72** [comment]
I'll check this.
The 1.4.13.1 was the latest at the time, but it took a while to open this issue here because I originally opened this for wrong project.

**Comment by yahman72** [comment]
seems to be fixed in v1.4.16.1
<pre>
[16.03.2016  7:28:31 c:\ta\appium\v1.4.16.1\]
> node node_modules\appium\lib\server\main.js --port 4700 --bootstrap-port 4800 --command-timeout 1800 --device-ready-timeout 120 --platform-name Android --platform-version 19 --automation-name Appium --log-timestamp --local-timezone --session-override --log c:\ta\appium\appium4700.log --log-level debug:debug
2016-03-16 07:29:38:761 - info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
2016-03-16 07:29:38:761 - info: Appium REST http interface listener started on 0.0.0.0:4700
2016-03-16 07:29:38:761 - info: [debug] Non-default server args: {"port":4700,"bootstrapPort":4800,"sessionOverride":true,"log":"c:\\ta\\appium\\appium4700.log","loglevel":"debug:debug","logTimestamp":true,"localTimezone":true,"androidDeviceReadyTimeout":"120","platformName":"Android","platformVersion":"19","automationName":"Appium","defaultCommandTimeout":1800}
2016-03-16 07:29:38:776 - info: Console LogLevel: debug
2016-03-16 07:29:38:776 - info: File LogLevel: debug
</pre>

**Comment by Astro03** [comment]
Favorite issues are ones that are already solved :)
